version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: wordpress
secrets:
  mysql_root_password:
    external: true
  wordpress_db_password:
    external: true

volumes:
  db_data:


# you can create secret using these commands

# echo "your_mysql_root_password" | docker secret create mysql_root_password -

# echo "wordpress_password" | docker secret create wordpress_db_password -

